Use a bootstrap env to get virtualenv<20
- Again, this is necessary because zc.buildout will fail inside a
  virtualenv that was created using virtualenv>=20, as that triggers the
  following import error when running buildout.

  $ bin/buildout -c deploy-all.cfg
  Creating directory '.../pmr2.buildout/eggs'.
  While:
    Installing.
    Loading extensions.

  An internal error occurred due to a bug in either zc.buildout or in a
  recipe being used:
  Traceback (most recent call last):
  ...
  RuntimeError: error trying to get system packages:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File ".../pmr2.buildout/lib64/python2.7/os.py", line 49, in <module>
      import posixpath as path
  ImportError: No module named posixpath

  Despite the fact that posixpath can normally be imported while inside
  the virtualenv created using virtualenv>=20.

- As Gentoo finally removed that legacy virtualenv from their official
  ebuild, this will leverage PyPI to get that old version installed into
  the bootstrap virtualenv<20 which then be used to create a Python 2
  virtualenv that would resolve that import issue.